baseURL = "http://asif.in/"
languageCode = "en-us"
title = "Asif"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Asif"
    description = "Think. Do."
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:asif@asif.in"
    name = "fas fa-envelope"
    weight = 1
